# Generated by Django 6.0.3 on 2026-04-16 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_id', models.UUIDField()),
                ('farmer_id', models.UUIDField()),
                ('image_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=200)),
                ('confidence_score', models.FloatField()),
                ('is_healthy', models.BooleanField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='diagnoses.diagnosis')),
            ],
        ),
    ]
