# Generated by Django 6.0.3 on 2026-04-16 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('crop_type', models.CharField(max_length=100)),
                ('area_ha', models.DecimalField(decimal_places=2, max_digits=8)),
                ('planted_date', models.DateField()),
                ('soil_type', models.CharField(blank=True, choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('silty', 'Silty'), ('peaty', 'Peaty'), ('chalky', 'Chalky')], max_length=20)),
                ('irrigation_method', models.CharField(blank=True, choices=[('drip', 'Drip'), ('sprinkler', 'Sprinkler'), ('flood', 'Flood'), ('manual', 'Manual')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('wilaya', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('disease', 'Disease')], default='healthy', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
