# Generated by Django 6.0.3 on 2026-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-processed_at']},
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
